### PR TITLE
avoid extra iteration

### PR DESCRIPTION
**Pull request by johnam**
a, b vars make it a bit easier to understand what’s going on since they hold the fib series in order

### CODE REVIEW

**Comment by icy** [comment]
Hey, I come across here because I got an email notification. That's really interesting, I haven't seen any reason maybe a Github buggy bug :dancer: 

Update: It's bc of a `star`. woh I didn't know that I give a star. Sorry for the noise.

**Comment by johnam** [comment]
@icy Haha, you are ⌚️ing this repo so you got the notification:

image

**Comment by icy** [comment]
Thanks @johnam I've fixed the setting :) It happened a bit long time ago and that's full of surprises when I got the email yesterday ;)

**Comment by judofyr** [comment]
Hah. This is a very old repo. Even I was surprised when I got a pull request here!

**Pull request merged**
